Fix Travis - use Ubuntu 18.04 instead of 14.04
fedora-infra/fmn pull request #308
Opened 2020-05-07 00:19 UTC by abitrolly

It also drops Python 3.4 from testing, because it is hardly used

2020-05-07 01:10 UTC, abitrolly commented
Travis is having problems https://travis-ci.community/t/failed-job-with-null-log/8500/

However, `lint` check may be failing legitimately.

2020-10-01 11:38 UTC, Zlopez requested changes
Only one small thing I found.

2020-10-01 11:38 UTC, Zlopez commented on .travis.yml
> +      env: TOXENV=py36
```suggestion
      env: TOXENV=py37
```

2020-10-02 08:54 UTC, abitrolly commented
@Zlopez fixed.

2020-10-02 14:45 UTC, Zlopez approved these changes

2021-01-12 14:53 UTC, pypingou commented
Let's get this in :)

2021-01-12 14:54 UTC, merged