Initial go at owned artifacts
fedora-infra/fmn pull request #648
Opened 2022-11-10 10:26 UTC by ryanlerch

Signed-off-by: Ryan Lerch <rlerch@redhat.com>

2022-11-17 09:10 UTC, abompard commented
Could you rebase and fix the conflict please?

2022-11-21 07:02 UTC, ryanlerch commented
> Could you rebase and fix the conflict please?

done.

not sure what the failing test is from, but its happening in the main branch too

2022-11-24 13:10 UTC, abompard requested changes

2022-11-24 13:10 UTC, abompard commented on fmn/api/distgit.py
> +            if firstpage.json()["pagination"]["pages"] > 1:
You could simplify that with a `while` loop. Check out `fmn.rules.services.distgit:DistGitService._all_values` for an example.

2022-11-25 04:49 UTC, ryanlerch commented on fmn/api/distgit.py
> +            if firstpage.json()["pagination"]["pages"] > 1:
okay... so i implemented this -- and it worked -- however it started to make the tests a lot more difficult
here is the branch with the change, and my attempts at redoing the tests

https://github.com/ryanlerch/fmn/tree/artifacts2-while-fullurl

basically, i previously used the same response twice with return_value, however, getting async coroutine StopIteration issues when trying to use side_effect (returning a list) to do multiple different return values.

is there something like responses for httpx async here to make this easier?

2022-11-28 06:33 UTC, ryanlerch commented on fmn/api/distgit.py
> +            if firstpage.json()["pagination"]["pages"] > 1:
I think i have ti sorted -- PR changes incoming soon

2022-11-28 07:09 UTC, ryanlerch commented
Ok! using the "next" url returned by pagure now in a while loop.

Got the tests working now too with pytest-httpx to mock the responses which works a lot better than what i was doing before.

Kept the initial commit in there, but intend to squash them into 1 before merging

2022-11-28 09:27 UTC, abompard requested changes

2022-11-28 09:27 UTC, abompard commented on fmn/api/distgit.py
> +            print(response.json())
Leftover here :-)

2022-11-28 09:27 UTC, abompard commented on fmn/api/distgit.py
> +                response = await self.client.get(response.json()["pagination"]["next"])
Yeah that works. Another way of doing it would have been to initialize `url` with the initial URL and refresh it with the next URL in the response, such as:
```python
url = f"{endpoint}?{urlencode(params)}"
while url:
    response = await self.client.get(url)
    response.raise_for_status()
    data = response.json()
    _appendArtifacts(data["projects"])
    url = data.get("pagination", {}).get("next")
```
This would allow you to avoid repeating yourself when writing the `client.get` calls, the `raise_for_status`, `_appendArtifacts` and such.

2022-11-28 09:27 UTC, abompard commented on fmn/api/distgit.py
> +        def _appendArtifacts(projects):
That's javascript naming scheme, please use `_append_artifacts`.

2022-11-28 09:27 UTC, abompard commented on tests/api/test_handlers.py
> +        print(httpx_mock.get_requests())
Not sure you need that either.

2022-11-28 10:41 UTC, ryanlerch commented
Thanks for the review!

Have implemented your changes, and squashed the commits now too.

2022-11-29 06:23 UTC, ryanlerch commented
Okay! Updated the tests to use respx (which was already being used) rather than pytest-httpx (which i introduced in a previous iteration of thius PR before knowing about respx)

2022-11-29 18:20 UTC, abompard approved these changes

2022-11-30 00:48 UTC, merged