Set the Copyright and Licensing info in all the files
fedora-infra/fmn pull request #832
Opened 2023-03-30 13:54 UTC by abompard

Make use of the [reuse](https://reuse.software) tool.

Also setup pre-commit to check all the files upon commit, with the following hooks:

- some basic hooks provided by pre-commit itself
- `black`
- `ruff`
- `reuse` for licenses

2023-03-30 15:05 UTC, nphilipp requested changes

2023-03-30 15:05 UTC, nphilipp commented on LICENSES/LicenseRef-Fedora-trademark.txt
> +This images includes the Fedora Trademarks.  You are granted the right to use the Package during the normal operation of software spins approved by the Fedora
Should probably be singular: “This image includes …”

2023-03-30 15:05 UTC, nphilipp commented on .coveragerc
> +# SPDX-FileCopyrightText: 2023 Fedora Infrastructure <admin@fedoraproject.org>
I’m not sure it should be like this. As far as I know, neither Fedora nor the Infrastructure Team are legal entities who can hold a copyright.

2023-03-30 15:05 UTC, nphilipp commented on DCO.txt
Why is this file removed?

2023-03-30 15:05 UTC, nphilipp commented on frontend/package-lock.json.license
I wonder if adding a copyright statement to an autogenerated lock file isn’t a bit overboard…

2023-03-30 15:05 UTC, nphilipp commented on tests/data/jsonschema_hyperschema.json.license
I guess these 👆👇 shouldn’t have a copyright header at all, they’re autogenerated API schemas downloaded from services partly outside of Fedora.

2023-03-30 15:17 UTC, abompard commented on frontend/package-lock.json.license
It is, but the tool insists that all files should have a license, and who am I to argue with lawyers? :-)

That said, I'll see if I can get away with just the license and no copyright.

2023-03-30 15:26 UTC, abompard commented on DCO.txt
I've replaced it with a link to developercertificate.org. Or at least I thought I did, but it was overwritten my one of my many `git restore`... Fixing.

2023-03-30 16:05 UTC, abompard commented on frontend/package-lock.json.license
Yep, I just noted that it's autogenerated.

2023-03-30 16:05 UTC, abompard commented on tests/data/jsonschema_hyperschema.json.license
I've replaced the copyright by a statement that it's autogenerated

2023-03-30 16:05 UTC, abompard commented on .coveragerc
> +# SPDX-FileCopyrightText: 2023 Fedora Infrastructure <admin@fedoraproject.org>
Fixed!

2023-03-30 16:05 UTC, abompard commented on LICENSES/LicenseRef-Fedora-trademark.txt
> +This images includes the Fedora Trademarks.  You are granted the right to use the Package during the normal operation of software spins approved by the Fedora
Fixed, thanks.

2023-03-31 09:02 UTC, nphilipp requested changes

2023-03-31 09:02 UTC, nphilipp commented on LICENSES/MIT.txt
> +Copyright (c) <year> <copyright holders>
I think this should be `Copyright Contributors to the Fedora Project`.

2023-03-31 09:02 UTC, nphilipp commented on tox.ini
> +passenv = HOME
What’s this for? Running `tox` works for me without it.

2023-03-31 15:16 UTC, nphilipp commented on tox.ini
> +passenv = HOME
Per convo in the chat: this makes running ruff as a pre-commit linter work.

2023-03-31 15:29 UTC, abompard commented on LICENSES/MIT.txt
> +Copyright (c) <year> <copyright holders>
Actually, [they recommend against doing that](https://reuse.software/faq/#license-templates). Weird, I know.

2023-03-31 16:09 UTC, nphilipp commented on LICENSES/MIT.txt
> +Copyright (c) <year> <copyright holders>
Okay then 😂

2023-03-31 16:10 UTC, nphilipp approved these changes
Looks good to me!

2023-03-31 16:47 UTC, merged