Better handling of sender errors
fedora-infra/fmn pull request #856
Opened 2023-04-12 17:09 UTC by abompard

Quite a few commits in this PR, I hope they are clear enough.

Now, when a protocol handler errors out, the sender component should shutdown (and get restarted by OpenShift)

2023-04-13 10:00 UTC, nphilipp requested changes

2023-04-13 10:00 UTC, nphilipp commented on fmn/sender/cli.py
> +        result = result.result()
Is it guaranteed that the `result` Future is done here?

```
…
asyncio.Future = class Future(builtins.object)
 |  asyncio.Future(*, loop=None)
 |  
 |  This class is *almost* compatible with concurrent.futures.Future.
 |  
 |  Differences:
 |  
 |  - result() and exception() do not take a timeout argument and
 |    raise an exception when the future isn't done yet.
…
```

Maybe let’s do this instead:

```
…
    if asyncio.isfuture(result):
        result = await result
…
```

2023-04-13 10:00 UTC, nphilipp commented on fmn/sender/cli.py
> +        raise HandlerError(f"the handler could not connect: {e}") from e
Why wrap the `TimeoutError` twice in a `HandlerError`?

2023-04-13 10:00 UTC, nphilipp commented on fmn/sender/handler.py
> +        self.closed = asyncio.get_event_loop().create_future()
Hmm, this looks like it’s only in place to ensure that any handler supports the `closed` Future, but it’s never really used except in `IRCHandler` where it dispatches to the aggregated `IRCClient` object and causes the `Handler.closed` Future to be thrown away. How about late initialization using a (cached) property? 

```
…
from functools import cached_property
…
class Handler:
    def __init__(self, config):
        self._config = config
        
   @cached_property
   def closed(self):
        """Default `closed` Future, can be overridden in child classes."""
        return asyncio.get_event_loop().create_future()
…
```

… and …

```
…
class IRCHandler(Handler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._client = IRCClient()

    @property
    def closed(self):
        return self._client.closed
…
```

2023-04-13 10:00 UTC, nphilipp commented on tests/conftest.py
> +        await cache.close()
👍

2023-04-13 10:00 UTC, nphilipp commented on tests/sender/test_irc.py
> +    assert handler.closed.done() is False
```suggestion
    assert not handler.closed.done()
```

2023-04-13 10:00 UTC, nphilipp commented on tests/sender/test_irc.py
> +    assert handler.closed.done() is False
```suggestion
    assert not handler.closed.done()
```

2023-04-14 08:55 UTC, abompard commented on fmn/sender/cli.py
> +        result = result.result()
Ah, but that would make the function async, which it can't be if used in `add_done_callback`. I'll do it a bit differently.

2023-04-14 09:02 UTC, abompard commented on fmn/sender/cli.py
> +        raise HandlerError(f"the handler could not connect: {e}") from e
I'm not sure I understand. The exception raised in the `TimeoutError` handler should not be caught by the second exception handler, no? Or is it? 
I can move the `HandlerError` exception handler first if it makes things clearer.

2023-04-14 09:03 UTC, abompard commented on fmn/sender/handler.py
> +        self.closed = asyncio.get_event_loop().create_future()
Yep, I'll do that!

2023-04-14 09:46 UTC, nphilipp commented on fmn/sender/cli.py
> +        result = result.result()
> Ah, but that would make the function async, …

Oops, totally missed that! 🙈

2023-04-14 09:57 UTC, nphilipp commented on fmn/sender/cli.py
> +        raise HandlerError(f"the handler could not connect: {e}") from e
> I'm not sure I understand. The exception raised in the `TimeoutError` handler should not be caught by the second exception handler, no? Or is it?

Hmm, I did some testing in the REPL and it looked like it was, but I did it again, now it doesn’t… Not sure what I did wrong before.

Still, I don’t understand why `except HandlerError` rewraps the exception in another `HandlerError`.

2023-04-14 10:02 UTC, abompard commented on fmn/sender/cli.py
> +        raise HandlerError(f"the handler could not connect: {e}") from e
Yeah, that's not really necessary, I'll fix that.

2023-04-14 10:40 UTC, nphilipp approved these changes
LGTM!

2023-04-14 10:44 UTC, merged